#pragma once

#include <Windows.h>

#define CODE_VKCODE(raw) HIWORD(raw)
#define CODE_SCCODE(raw) LOWORD(raw)
#define MAKECOMCODE(sccode, vkcode) MAKELONG(sccode, vkcode)

// =============================
// MAKECOMCODE( ScanCode, VKCode )
// =============================


//-------------------
// Characters
//-------------------
#define KEY_A MAKECOMCODE(30, (WORD)'A')
#define KEY_B MAKECOMCODE(48, (WORD)'B')
#define KEY_C MAKECOMCODE(46, (WORD)'C')
#define KEY_D MAKECOMCODE(32, (WORD)'D')
#define KEY_E MAKECOMCODE(18, (WORD)'E')
#define KEY_F MAKECOMCODE(33, (WORD)'F')
#define KEY_G MAKECOMCODE(34, (WORD)'G')
#define KEY_H MAKECOMCODE(35, (WORD)'H')
#define KEY_I MAKECOMCODE(23, (WORD)'I')
#define KEY_J MAKECOMCODE(36, (WORD)'J')
#define KEY_K MAKECOMCODE(37, (WORD)'K')
#define KEY_L MAKECOMCODE(38, (WORD)'L')
#define KEY_M MAKECOMCODE(50, (WORD)'M')
#define KEY_N MAKECOMCODE(49, (WORD)'N')
#define KEY_O MAKECOMCODE(24, (WORD)'O')
#define KEY_P MAKECOMCODE(25, (WORD)'P')
#define KEY_Q MAKECOMCODE(16, (WORD)'Q')
#define KEY_R MAKECOMCODE(19, (WORD)'R')
#define KEY_S MAKECOMCODE(31, (WORD)'S')
#define KEY_T MAKECOMCODE(20, (WORD)'T')
#define KEY_U MAKECOMCODE(22, (WORD)'U')
#define KEY_V MAKECOMCODE(47, (WORD)'V')
#define KEY_W MAKECOMCODE(17, (WORD)'W')
#define KEY_X MAKECOMCODE(45, (WORD)'X')
#define KEY_Y MAKECOMCODE(21, (WORD)'Y')
#define KEY_Z MAKECOMCODE(44, (WORD)'Z')

//-------------------
// Numbers
//-------------------
#define KEY_1 MAKECOMCODE(2, (WORD)'1')
#define KEY_2 MAKECOMCODE(3, (WORD)'2')
#define KEY_3 MAKECOMCODE(4, (WORD)'3')
#define KEY_4 MAKECOMCODE(5, (WORD)'4')
#define KEY_5 MAKECOMCODE(6, (WORD)'5')
#define KEY_6 MAKECOMCODE(7, (WORD)'6')
#define KEY_7 MAKECOMCODE(8, (WORD)'7')
#define KEY_8 MAKECOMCODE(9, (WORD)'8')
#define KEY_9 MAKECOMCODE(10, (WORD)'9')
#define KEY_0 MAKECOMCODE(11, (WORD)'0')



//-------------------
// Numeric keypad
//-------------------
#define KEY_NUMLOCK  MAKECOMCODE(69, VK_NUMLOCK)

#define KEY_NUMPAD0  MAKECOMCODE(82, VK_NUMPAD0)
#define KEY_NUMPAD1  MAKECOMCODE(79, VK_NUMPAD1)
#define KEY_NUMPAD2  MAKECOMCODE(80, VK_NUMPAD2)
#define KEY_NUMPAD3  MAKECOMCODE(81, VK_NUMPAD3)
#define KEY_NUMPAD4  MAKECOMCODE(75, VK_NUMPAD4)
#define KEY_NUMPAD5  MAKECOMCODE(76, VK_NUMPAD5)
#define KEY_NUMPAD6  MAKECOMCODE(77, VK_NUMPAD6)
#define KEY_NUMPAD7  MAKECOMCODE(71, VK_NUMPAD7)
#define KEY_NUMPAD8  MAKECOMCODE(72, VK_NUMPAD8)
#define KEY_NUMPAD9  MAKECOMCODE(73, VK_NUMPAD9)

#define KEY_DIVIDE   MAKECOMCODE(53, VK_DIVIDE)
#define KEY_MULTIPLY MAKECOMCODE(55, VK_MULTIPLY)
#define KEY_SUBTRACT MAKECOMCODE(74, VK_SUBTRACT)
#define KEY_ADD      MAKECOMCODE(78, VK_ADD)
#define KEY_DECIMAL  MAKECOMCODE(83, VK_DECIMAL)

#define KEY_CLEAR    MAKECOMCODE(76, VK_CLEAR)


//-------------------
// Symbol keys
//-------------------
#define KEY_OEM_MINUS  MAKECOMCODE(12, VK_OEM_MINUS)  // -=
#define KEY_OEM_7      MAKECOMCODE(13, VK_OEM_7)  // ^~
#define KEY_OEM_5      MAKECOMCODE(125, VK_OEM_5) // \|

#define KEY_OEM_3      MAKECOMCODE(26, VK_OEM_3)  // @`
#define KEY_OEM_4      MAKECOMCODE(27, VK_OEM_4)  // [{

#define KEY_OEM_PLUS   MAKECOMCODE(39, VK_OEM_PLUS)  // ;+
#define KEY_OEM_1      MAKECOMCODE(40, VK_OEM_1)  // :*
#define KEY_OEM_6      MAKECOMCODE(43, VK_OEM_6)  // ]}

#define KEY_OEM_2      MAKECOMCODE(53, VK_OEM_2)  // /?
#define KEY_OEM_102    MAKECOMCODE(115, VK_OEM_102) // \_
#define KEY_OEM_COMMA  MAKECOMCODE(51, VK_OEM_COMMA)  // ,<
#define KEY_OEM_PERIOD MAKECOMCODE(52, VK_OEM_PERIOD)  // .>


//-------------------
// Modifier keys
//-------------------
#define KEY_LCONTROL MAKECOMCODE(29, VK_LCONTROL)
#define KEY_RCONTROL MAKECOMCODE(29, VK_RCONTROL)
#define KEY_LSHIFT   MAKECOMCODE(42, VK_LSHIFT)
#define KEY_RSHIFT   MAKECOMCODE(54, VK_RSHIFT)
#define KEY_LMENU    MAKECOMCODE(56, VK_LMENU)
#define KEY_RMENU    MAKECOMCODE(56, VK_RMENU)


//-------------------
// Function Keys
//-------------------
#define KEY_F1 MAKECOMCODE(59, VK_F1)
#define KEY_F2 MAKECOMCODE(60, VK_F2)
#define KEY_F3 MAKECOMCODE(61, VK_F3)
#define KEY_F4 MAKECOMCODE(62, VK_F4)
#define KEY_F5 MAKECOMCODE(63, VK_F5)
#define KEY_F6 MAKECOMCODE(64, VK_F6)
#define KEY_F7 MAKECOMCODE(65, VK_F7)
#define KEY_F8 MAKECOMCODE(66, VK_F8)
#define KEY_F9 MAKECOMCODE(67, VK_F9)
#define KEY_F10 MAKECOMCODE(68, VK_F10)
#define KEY_F11 MAKECOMCODE(87, VK_F11)
#define KEY_F12 MAKECOMCODE(88, VK_F12)

#define KEY_F13 MAKECOMCODE(100, VK_F13)
#define KEY_F14 MAKECOMCODE(101, VK_F14)
#define KEY_F15 MAKECOMCODE(102, VK_F15)
#define KEY_F16 MAKECOMCODE(103, VK_F16)
#define KEY_F17 MAKECOMCODE(104, VK_F17)
#define KEY_F18 MAKECOMCODE(105, VK_F18)
#define KEY_F19 MAKECOMCODE(106, VK_F19)
#define KEY_F20 MAKECOMCODE(107, VK_F20)
#define KEY_F21 MAKECOMCODE(108, VK_F21)
#define KEY_F22 MAKECOMCODE(109, VK_F22)
#define KEY_F23 MAKECOMCODE(110, VK_F23)
#define KEY_F24 MAKECOMCODE(118, VK_F24)


//-------------------
// Arrow keys
//-------------------
#define KEY_LEFT  MAKECOMCODE(75, VK_LEFT)
#define KEY_UP    MAKECOMCODE(72, VK_UP)
#define KEY_RIGHT MAKECOMCODE(77, VK_RIGHT)
#define KEY_DOWN  MAKECOMCODE(80, VK_DOWN)


//-------------------
// Others
//-------------------
#define KEY_ESCAPE   MAKECOMCODE(1, VK_ESCAPE)
#define KEY_OEM_AUTO MAKECOMCODE(41, VK_OEM_AUTO) // Zenkaku/Hankaku ON
#define KEY_OEM_ENLW MAKECOMCODE(41, VK_OEM_ENLW) //                 OFF
#define KEY_GRAVE    MAKECOMCODE(41, VK_OEM_3)    // US Grave Accent

#define KEY_TAB MAKECOMCODE(15, VK_TAB)

#define KEY_OEM_ATTN MAKECOMCODE(58, VK_OEM_ATTN) // Japanese CapsLock
#define KEY_CAPITAL  MAKECOMCODE(58, VK_CAPITAL)  // US CapsLock / Japanese Shift+CapsLock 

#define KEY_LWIN MAKECOMCODE(91, VK_LWIN)
#define KEY_RWIN MAKECOMCODE(92, VK_RWIN)
#define KEY_APPS MAKECOMCODE(93, VK_APPS)

#define KEY_NONCONVERT MAKECOMCODE(123, VK_NONCONVERT)
#define KEY_CONVERT   MAKECOMCODE(121, VK_CONVERT)

#define KEY_OEM_COPY MAKECOMCODE(112, VK_OEM_COPY) // Katakana/Hiragana

#define KEY_SNAPSHOT MAKECOMCODE(55, VK_SNAPSHOT)
#define KEY_SCROLL   MAKECOMCODE(70, VK_SCROLL)
#define KEY_PAUSE    MAKECOMCODE(69, VK_PAUSE)

#define KEY_INSERT MAKECOMCODE(82, VK_INSERT)
#define KEY_DELETE MAKECOMCODE(83, VK_DELETE)

#define KEY_HOME MAKECOMCODE(71, VK_HOME)
#define KEY_END  MAKECOMCODE(79, VK_END)

#define KEY_PRIOR MAKECOMCODE(73, VK_PRIOR) // PageUp
#define KEY_NEXT  MAKECOMCODE(81, VK_NEXT)  // PageDown



//-------------------
// Media
//-------------------
#define KEY_MEDIA_STOP       MAKECOMCODE(0, VK_MEDIA_STOP)
#define KEY_MEDIA_PREV_TRACK MAKECOMCODE(0, VK_MEDIA_PREV_TRACK)
#define KEY_MEDIA_PLAY_PAUSE MAKECOMCODE(0, VK_MEDIA_PLAY_PAUSE)
#define KEY_MEDIA_NEXT_TRACK MAKECOMCODE(0, VK_MEDIA_NEXT_TRACK)

#define KEY_VOLUME_MUTE MAKECOMCODE(0, VK_VOLUME_MUTE)
#define KEY_VOLUME_UP   MAKECOMCODE(0, VK_VOLUME_UP)
#define KEY_VOLUME_DOWN MAKECOMCODE(0, VK_VOLUME_DOWN)

// #define KEY_ MAKECOMCODE(, )


//-------------------
// Mouse
//-------------------
#define VK_WHEELUP     156
#define VK_WHEELDOWN   157
#define VK_HWHEELLEFT  158
#define VK_HWHEELRIGHT 159

#define KEY_LBUTTON MAKECOMCODE(0, VK_LBUTTON)
#define KEY_RBUTTON MAKECOMCODE(0, VK_RBUTTON)
#define KEY_MBUTTON MAKECOMCODE(0, VK_MBUTTON)
#define KEY_XBUTTON1 MAKECOMCODE(0, VK_XBUTTON1)
#define KEY_XBUTTON2 MAKECOMCODE(0, VK_XBUTTON2)

#define KEY_WHEELUP     MAKECOMCODE(0, VK_WHEELUP)
#define KEY_WHEELDOWN   MAKECOMCODE(0, VK_WHEELDOWN)
#define KEY_HWHEELLEFT  MAKECOMCODE(0, VK_HWHEELLEFT)
#define KEY_HWHEELRIGHT MAKECOMCODE(0, VK_HWHEELRIGHT)

